apiVersion: v1
kind: Service
metadata:
  name: {{ include "metaflow-ui.fullname" . }}
  labels:
    {{- include "metaflow-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.uiBackend.service.type }}
  ports:
    - port: {{ .Values.uiBackend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "metaflow-ui.selectorLabels" . | nindent 4 }}
