apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metaflow-ui.fullname" . }}
  labels:
    {{- include "metaflow-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.uiBackend.replicaCount }}
  selector:
    matchLabels:
      {{- include "metaflow-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.uiBackend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metaflow-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metaflow-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.uiBackend.image.name }}:{{ .Values.uiBackend.image.tag | default .Chart.AppVersion }}"
          command: ["/opt/latest/bin/python3", "-m", "services.ui_backend_service.ui_server" ]
          imagePullPolicy: {{ .Values.uiBackend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/ping
              port: http
          readinessProbe:
            httpGet:
              path: /api/ping
              port: http
          {{- with .Values.uiBackend.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range .Values.uiBackend.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            - name: UI_ENABLED
              value: "1"
            - name: PATH_PREFIX
              value: "/api"
            - name: MF_DATASTORE_ROOT
              value: {{ .Values.uiBackend.metaflowDatastoreSysRootS3 | quote }}
            - name: METAFLOW_DATASTORE_SYSROOT_S3
              value: {{ .Values.uiBackend.metaflowDatastoreSysRootS3 | quote }}
            {{- if .Values.uiBackend.metaflowS3EndpointURL }}
            - name: METAFLOW_S3_ENDPOINT_URL
              value: {{ .Values.uiBackend.metaflowS3EndpointURL | quote }}
            {{- end }}
            - name: LOGLEVEL
              value: "DEBUG"
            - name: METAFLOW_SERVICE_URL
              value: {{ .Values.uiBackend.metaflowServiceURL | quote }}
            - name: METAFLOW_DEFAULT_DATASTORE
              value: "s3"
            - name: METAFLOW_DEFAULT_METADATA
              value: "service"
            {{- include "metaflow-ui.metadatadbEnvVars" . | nindent 12 }}
          resources:
            {{- toYaml .Values.uiBackend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
