apiVersion: v2
appVersion: v2.4.13
description: A Helm chart to deploy Metadata Service for Metaflow
name: metaflow-service
type: application
version: 0.2.3
maintainers:
  - name: Savin Goyal
    email: savin@outerbounds.co
  - name: Oleg Avdeev
    email: oleg@outerbounds.co
keywords:
  - metaflow
  - metadata
  - service
sources:
  - https://github.com/Netflix/metaflow-service
  - https://github.com/outerbounds/metaflow-tools
icon: https://metaflow.org/images/metaflow.svg
